import Footer from '@/components/layout/Footer';
import Header from '@/components/layout/Header';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Welcome to ProgressHub!',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className='flex flex-col h-screen justify-between'>
      <Header />
      <main className='col-span-3 lg:col-span-4'>{children}</main>
      <Footer />
    </div>
  );
}
