import { Button } from '@/components/ui/button';
import { ArrowLeftIcon } from 'lucide-react';
import type { Metadata } from 'next';
import Link from 'next/link';

export const metadata: Metadata = {
  title: 'Приєднатися до робочого простору',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className='h-screen'>
      <header className='w-full py-6 container flex items-center justify-between px-4 md:px-6'>
        <Button asChild variant='outline'>
          <Link className='flex' href='/'>
            <ArrowLeftIcon className='h-6 w-6' />
            <span>Повернутися до ProgressHub</span>
          </Link>
        </Button>
      </header>
      <main className='grid place-items-center h-[80vh]'>{children}</main>
    </div>
  );
}
