import WorkspaceSideBar from '@/components/workspace/WorkspaceSideBar';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Home',
  description: 'Generated by create next app',
};

export default async function RootLayout(
  props: Readonly<{
    children: React.ReactNode;
    params: { workspaceId: string };
  }>
) {
  const params = await props.params;

  const { children } = props;

  return (
    <div className='flex flex-col h-screen justify-between'>
      <div className='mb-auto p-8 pt-2 md:p-8 grid lg:grid-cols-5'>
        <WorkspaceSideBar workspaceId={params.workspaceId} />
        <main className='lg:col-span-4'>{children}</main>
      </div>
    </div>
  );
}
