import Footer from '@/components/layout/Footer';
import SideBar from '@/components/layout/Sidebar';
import { auth } from '@/lib/auth/utils';
import prisma from '@/lib/db';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Home',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: { workspaceId: string };
}>) {
  let isUserMember = false;
  const session = await auth();
  const userId = session?.user?.id;

  if (userId) {
    const workspaceUsers = await prisma.workspaceMembers.findFirst({
      where: {
        workspaceId: params.workspaceId,
        userId: userId,
      },
      select: {
        id: true,
      },
    });

    if (workspaceUsers) isUserMember = true;
  }

  //TODO: Add a better UI for this
  if (!isUserMember) return <main>You are not a member of this workspace</main>;

  return (
    <div className='flex flex-col h-screen justify-between'>
      <div className='mb-auto p-8 pt-2 md:p-8 grid lg:grid-cols-5'>
        <SideBar workspaceId={params.workspaceId} />
        <main className='lg:col-span-4'>{children}</main>
      </div>
      <Footer />
    </div>
  );
}
