import { auth } from '@/lib/auth/utils';
import { prisma } from '@/lib/db/index';
import type { Metadata } from 'next';
import { cookies } from 'next/headers';
import { redirect } from 'next/navigation';

export const metadata: Metadata = {
  title: 'Welcome to ProgressHub!',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = cookies();
  const session = await auth();

  if (session) {
    const lastVisitedWorkspace = cookieStore.get('lastVisitedWorkspace');
    if (lastVisitedWorkspace) return redirect(`/${lastVisitedWorkspace}`);

    const workspace = await prisma.workspace.findFirst({
      where: {
        members: {
          some: {
            userId: session.user?.id,
          },
        },
      },
      select: {
        id: true,
      },
    });
    if (workspace) return redirect(`/workspace/${workspace.id}`);
    return redirect('/create');
  }

  return <>{children}</>;
}
